---
- name: Install nginx
  hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3.9

  tasks:

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
