---
- name: Install htop
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Install Python 3.9
      ansible.builtin.raw: |
        apt-get update
        apt-get install -y python3.9
      changed_when: false

    - name: Install htop
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: true
